import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers';
import NextChatSDKBootstrap from '@/NextChatSDKBookstrap';
import { baseURL } from '@/baseUrl';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<head>
				<NextChatSDKBootstrap baseUrl={baseURL} />
			</head>
			<Providers>
				<body>{children}</body>
			</Providers>
		</html>
	);
}
